#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    a1=0
    o1=0
    app1=0
    org1=0
    for i in range(0,len(apples),1):
        a1=a+apples[i]
        if a1>=s and a1<=t:
            app1 +=1
            #print("a1 ",a1)
            #print("app1 ",app1)
        a1=0
    for j in range(0,len(oranges),1):
        o1=b+oranges[j]
        if o1>=s and o1<=t:
            org1 +=1
            #print("o1 ",o1)
            #print("org1 ",org1)
        o1=0
    print(app1)
    print(org1)




if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)

